CREATE TABLE IF NOT EXISTS version (id INTEGER);

CREATE TABLE IF NOT EXISTS last_write (id INTEGER);

CREATE TABLE IF NOT EXISTS date_range (first INTEGER, last INTEGER);

CREATE TABLE IF NOT EXISTS story (
    id INTEGER PRIMARY KEY,
    title TEXT NULL COLLATE NOCASE,
    url TEXT NULL COLLATE NOCASE,
    time INTEGER
);

CREATE INDEX ix_time ON story (time);